[package]
name = "projections"
version = "1.1.1"
edition = "2024"
description = "Macro-free pin projections because why not?"
license = "Apache-2.0 OR BSL-1.0 OR MIT"
documentation = "https://docs.rs/projections"
homepage = "https://github.com/ardaku/projections/releases"
repository = "https://github.com/ardaku/projections/"
include = [
    "/LICENSE_APACHE",
    "/LICENSE_BOOST",
    "/LICENSE_MIT",
    "/README.md",
    "/examples/*",
    "/src/*",
]
keywords = ["pin", "lite", "projection", "safe", "structural"]
categories = [
    "asynchronous",
    "no-std",
    "no-std::no-alloc",
    "rust-patterns",
    "data-structures",
]
rust-version = "1.91"
readme = "README.md"

[dev-dependencies.as_repr]
version = "1.11.0"

[dev-dependencies.pasts]
version = "0.14.3"
