[package]
name = "projections"
version = "0.2.0"
edition = "2024"
description = "Macro-free pin projections because why not?"
license = "Apache-2.0 OR BSL-1.0 OR MIT"
documentation = "https://docs.rs/projections"
homepage = "https://github.com/ardaku/projections/releases"
repository = "https://github.com/ardaku/projections/"
include = ["Cargo.toml", "src/", "examples/", "README.md"]
keywords = ["pin", "lite", "projection", "safe", "structural"]
categories = [
    "asynchronous",
    "no-std",
    "no-std::no_alloc",
    "rust-patterns",
    "data-structures",
]
rust-version = "1.91"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies.as_repr]
version = "1.10.0"
path = "../../AldaronLau/as_repr"

[dev-dependencies.pasts]
version = "0.14.3"
